DROP TABLE BOARD;
CREATE TABLE BOARD
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(32),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(100),
	HIT NUMBER,  -- 조회수
	IP VARCHAR2(20),  -- 작성자IP
	FILENAME VARCHAR2(300),
	STATE NUMBER,  -- 상태(정상: 0, 삭제: -1)
	POSTDATE DATE,
	LASTMODIFIED DATE  -- 최종수정일
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;
