DROP TABLE REPLY;
CREATE TABLE REPLY
(
	IDX NUMBER,  -- 댓글번호
	AUTHOR VARCHAR2(50),  -- 작성자
	CONTENT VARCHAR2(4000),  -- 내용
	IP VARCHAR2(20),  -- 작성자IP
	BOARD_IDX NUMBER,  -- 원글의 번호
	POSTDATE DATE  -- 작성일
);

ALTER TABLE REPLY ADD CONSTRAINT REPLY_PK PRIMARY KEY(IDX);
--ALTER TABLE REPLY ADD CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(BOARD_IDX) REFERENCES BOARD(NO);

DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE REPLY_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE;

