DROP TABLE BOARD;
CREATE TABLE BOARD
(
	NO NUMBER PRIMARY KEY,
	WRITER VARCHAR2(32),
	TITLE VARCHAR2(100),
	CONTENT VARCHAR2(100),
    IP VARCHAR2(15),
	ORIGIN_FILENAME VARCHAR2(256),
    SAVE_FILENAME VARCHAR2(40),  -- 파일명 32바이트, 확장자 8바이트
	POSTDATE DATE
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE; 
